### ISSUE TITLE
Are you tested it on 4b?

### ISSUE THREAD

**Issue by moinologics** [MkLHX/AP_STA_RPI_SAME_WIFI_CHIP#1]
Will this work on raspberry Pi 4B?

**Comment by MkLHX** [comment]
Hello @ProgrammingPlanet  i don't now can't test it.
Have you tried?

**Comment by wohaoa** [comment]
@MkLHX I executed them in 3B+,   AP works, but STA does not .o(╥﹏╥)o

**Comment by MkLHX** [comment]
And what the error message or something about the error?
STA process is just to write SSID and passphrase in wpa_supplicant.conf so take a look if you have a typo or not on it.

**Comment by wohaoa** [comment]
@MkLHX 
I executed the script without error
![47b3c6d4f96477c8a295a604b6a258a](https://user-images.githubusercontent.com/7288685/133769773-e55ed8d2-b6f1-48c1-9f94-a6413c23e95a.jpg)
But I restart the Raspberry Pi, the network connection icon is grey
![9043656748a1832d7881f95e3007518](https://user-images.githubusercontent.com/7288685/133770015-8fc02afd-404d-4ad7-9a79-88ff46a21444.jpg)

**Comment by wohaoa** [comment]
@MkLHX 
Sorry, I tested it, the icon is gray, but AP+STA works fine, I think it's a UI bug

**Comment by MkLHX** [comment]
ok but this don't tell me if you have an error or not on your wifi credentials.

when you hit ifconfig did you get AP0 and WLAN0 interfaces?

Are you sure wpa_supplicant service is used on your raspberry pi distribution?

ap_sta_config.sh is used only on raspbian os lite in my side.

**Comment by wohaoa** [comment]
@MkLHX 
Sorry, I tested it, the icon is gray, but I can ping the network, I think the network connection icon is gray is a bug in the UI.
![image](https://user-images.githubusercontent.com/7288685/133775118-2fadc836-7562-44bb-bc2d-9c884d956644.png)
But now I found another problem, I use another PC to connect to wifi hotspot **ap_ssid**, I can ping through 192.168.10.1, but can not ping the network
![image](https://user-images.githubusercontent.com/7288685/133776008-a5fe7c51-a81d-4073-9328-b5f2d47d4645.png)

**Comment by MkLHX** [comment]
So you're connected on both STA and AP.

The red cross on desktop I can't say why it's present because I never use desktop OS on RPI.

So ap_sta_config.sh works.

**Comment by wohaoa** [comment]
> So you're connected on both STA and AP.
> 
> The red cross on desktop I can't say why it's present because I never use desktop OS on RPI.
> 
> So ap_sta_config.sh works.
@MkLHX 
I think it is working, but I tested other devices connected to this AP and they can't access the network，I don't know why there is this problem

**Comment by MkLHX** [comment]
@wohaoa you're talking about what? 
When you're connected to the AP if the raspberry pi doesn't already have an WAN access it's normal you can get access to WAN.

I don't undestand what are you trying to do. 

The goal of this script is to allow raspbery pi to have both AP and STA mode and to use it in IoT devices and allow user to setting network.

**Comment by wohaoa** [comment]
@MkLHX sorry, I understand what you mean, use it in IoT devices and allow user to setting network is perfectly ok ，my intention is to use it as a network hotspot

**Comment by MkLHX** [comment]
sorry i never tried to use this script in this use case. And i don't have any time to test and fix this part.

**Comment by wohaoa** [comment]
> sorry i never tried to use this script in this use case. And i don't have any time to test and fix this part.

@MkLHX  I see, thanks!

**Comment by wohaoa** [comment]
> Will this work on raspberry Pi 4B?

I have tested it in 4B and it works fine

**Comment by MkLHX** [comment]
Great to ear !

**Comment by MkLHX** [comment]
so i close the issue ;-)
