### ISSUE TITLE
bash: line 362: /usr/bin/systemctl: No such file or directory

### ISSUE THREAD

**Issue by orvio-craig** [MkLHX/AP_STA_RPI_SAME_WIFI_CHIP#11]
Running on Pi 4B, Raspbian GNU/Linux 10 (buster).

```
Manage AP + STA modes on Raspberry Pi with the same wifi chip


Populate /etc/udev/rules.d/70-persistent-net.rules


Populate /etc/dnsmasq.conf


Populate /etc/hostapd/hostapd.conf


Populate /etc/default/hostapd


Populate /etc/wpa_supplicant/wpa_supplicant.conf


Populate /etc/network/interfaces


Populate /bin/manage-ap0-iface.sh


Populate /bin/rpi-wifi.sh


Unmask and enable dnsmasq.service / hostapd.service

bash: line 362: /usr/bin/systemctl: No such file or directory
```

**Comment by aaronjamt** [comment]
Can you post the output of `which systemctl`? That file should exist on any Raspbian installation, have you modified system files at all?

**Comment by MkLHX** [comment]
Hi sorry for the late reply,

I think this isn't an issue from the repo code. Systemctl is a tool provided by OS raspbian.
As @aaronjamt said can you check 
```whereis systemctl```
 or 
 ```which systemctl```
  commands return.

**Comment by MkLHX** [comment]
@TokenZero did you get the notification about our answers?

**Comment by evandene** [comment]
Trying to install RPI-wifi on my latest Raspbian but get a message from line 363, 
"Unmask and enable dnsmasq.service / hostapd.service
bash: line 362: /usr/bin/systemctl: No such file or directory
I checked the with whereis systemctl and it seems to be in the /bin directory and not in /usr/bin directory.
Is there a workaround?
Thanks in advance for your support

**Comment by MkLHX** [comment]
can you check
```whereis systemctl```
or
```which systemctl```
commands return.

**Comment by aaronjamt** [comment]
> Trying to install RPI-wifi on my latest Raspbian but get a message from line 363, "Unmask and enable dnsmasq.service / hostapd.service bash: line 362: /usr/bin/systemctl: No such file or directory I checked the with whereis systemctl and it seems to be in the /bin directory and not in /usr/bin directory. Is there a workaround? Thanks in advance for your support

You _could_ edit the file, change line 362 from `/usr/bin/systemctl` to `/bin/systemctl`. You could also create a symlink from `/bin/systemctl` to `/usr/bin/systemctl` with `sudo ln -s /bin/systemctl /usr/bin/systemctl`.

**Comment by MkLHX** [comment]
i close the issue due to unactivity
