### ISSUE TITLE
Change client SSID and pwd without internet

### ISSUE THREAD

**Issue by FunkyKwak** [MkLHX/AP_STA_RPI_SAME_WIFI_CHIP#2]
Hi,

Thanks a lot for tour work, it helped me a lot !

I just have a question : how can I change the client SSID and password without internet connection ?
Cause without internet I cannot use the curl command I used to setup it first.

Thanks in avance !

**Comment by FunkyKwak** [comment]
I finaly found out how : simply clone the repo on my server, and run ap_sta_config.sh as described in the readme.
Sorry if the question was stupid. And thanks again for your work !

**Comment by MkLHX** [comment]
hello @FunkyKwak 
yeah that the limitation of the no install process ;-)

But you can download / clone the repo before to be sure to have the script elsewhere.

Good to see you finally find a solution to your issue ^^
